[build]
  functions = "netlify/functions"
  publish = "frontend"

[[redirects]]
  from = "/api/playlist/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200